module/xwindow: add missing header
modules/xwindow.c:142:29: error: implicit declaration of function 'basename' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    m->application = strdup(basename(cmd));
                            ^
modules/xwindow.c:142:29: error: incompatible integer to pointer conversion passing 'int' to parameter of type 'const char *' [-Werror,-Wint-conversion]
    m->application = strdup(basename(cmd));
                            ^~~~~~~~~~~~~
/usr/include/string.h:87:26: note: passing argument to parameter here
char    *strdup(const char *) __malloc_like;
                            ^
2 errors generated.