particle: add missing header
particle.c:223:17: error: implicit declaration of function 'sigemptyset' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                sigemptyset(&mask);
                ^
particle.c:225:60: error: use of undeclared identifier 'SIG_DFL'
                const struct sigaction sa = {.sa_handler = SIG_DFL};
                                                           ^
particle.c:225:40: error: variable has incomplete type 'const struct sigaction'
                const struct sigaction sa = {.sa_handler = SIG_DFL};
                                       ^
particle.c:225:30: note: forward declaration of 'struct sigaction'
                const struct sigaction sa = {.sa_handler = SIG_DFL};
                             ^
particle.c:226:21: error: implicit declaration of function 'sigaction' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                if (sigaction(SIGINT, &sa, NULL) < 0 ||
                    ^
particle.c:226:31: error: use of undeclared identifier 'SIGINT'
                if (sigaction(SIGINT, &sa, NULL) < 0 ||
                              ^
particle.c:227:31: error: use of undeclared identifier 'SIGTERM'
                    sigaction(SIGTERM, &sa, NULL) < 0 ||
                              ^
particle.c:228:31: error: use of undeclared identifier 'SIGCHLD'
                    sigaction(SIGCHLD, &sa, NULL) < 0 ||
                              ^
particle.c:229:21: error: implicit declaration of function 'sigprocmask' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                    sigprocmask(SIG_SETMASK, &mask, NULL) < 0)
                    ^
particle.c:229:33: error: use of undeclared identifier 'SIG_SETMASK'
                    sigprocmask(SIG_SETMASK, &mask, NULL) < 0)
                                ^
9 errors generated.