module/script: add missing header
modules/script.c:413:9: error: implicit declaration of function 'sigemptyset' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        sigemptyset(&mask);
        ^
modules/script.c:415:52: error: use of undeclared identifier 'SIG_DFL'
        const struct sigaction sa = {.sa_handler = SIG_DFL};
                                                   ^
modules/script.c:415:32: error: variable has incomplete type 'const struct sigaction'
        const struct sigaction sa = {.sa_handler = SIG_DFL};
                               ^
modules/script.c:415:22: note: forward declaration of 'struct sigaction'
        const struct sigaction sa = {.sa_handler = SIG_DFL};
                     ^
modules/script.c:416:13: error: implicit declaration of function 'sigaction' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        if (sigaction(SIGINT, &sa, NULL) < 0 ||
            ^
modules/script.c:416:23: error: use of undeclared identifier 'SIGINT'
        if (sigaction(SIGINT, &sa, NULL) < 0 ||
                      ^
modules/script.c:417:23: error: use of undeclared identifier 'SIGTERM'
            sigaction(SIGTERM, &sa, NULL) < 0 ||
                      ^
modules/script.c:418:23: error: use of undeclared identifier 'SIGCHLD'
            sigaction(SIGCHLD, &sa, NULL) < 0 ||
                      ^
modules/script.c:419:13: error: implicit declaration of function 'sigprocmask' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
            sigprocmask(SIG_SETMASK, &mask, NULL) < 0)
            ^
modules/script.c:419:25: error: use of undeclared identifier 'SIG_SETMASK'
            sigprocmask(SIG_SETMASK, &mask, NULL) < 0)
                        ^
modules/script.c:503:14: error: use of undeclared identifier 'SIGINT'
            {SIGINT, 2, "SIGINT"},
             ^
modules/script.c:504:14: error: use of undeclared identifier 'SIGTERM'
            {SIGTERM, 5, "SIGTERM"},
             ^
modules/script.c:505:14: error: use of undeclared identifier 'SIGKILL'
            {SIGKILL, 0, "SIGKILL"},
             ^
modules/script.c:508:38: error: invalid application of 'sizeof' to an incomplete type 'const struct (anonymous struct at modules/script.c:498:22) []'
        for (size_t i = 0; i < sizeof(sig_info) / sizeof(sig_info[0]); i++) {
                                     ^~~~~~~~~~
modules/script.c:517:13: error: implicit declaration of function 'killpg' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
            killpg(pid, signo);
            ^
14 errors generated.